name: Sample Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash
