name: First Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main_test

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: src/resources/reports/
