name: High Level Regression
on:
  workflow_dispatch:
    inputs:
      BROWSER:
        description: 'Choose Browser'
        type: choice
        options:
          - 'Chrome'
          - 'Edge'
          - 'Firefox'
        default: 'Chrome'
        required: true

      EMAIL_TO:
        description: 'Enter emails to send to.'
        default: 'kcvijay121@gmail.com'
        required: true

      SUBJECT:
        description: 'Enter Subject of the Email'
        default: Chrome High Level Regression
        required: true

#  push:
#    branches:
#      - main
env:
  email_to: 'kcvijay121@gmail.com'
  subject: 'Chrome High Level Regression'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute on Chrome
        if: github.event.inputs.BROWSER == 'Chrome'
        run: |
          echo ${{ github.event.inputs.BROWSER }}
          mvn -B package --file pom.xml -Dbrowser="chrome"

      - name: Execute on Edge
        if: github.event.inputs.BROWSER == 'Edge'
        run: |
          echo ${{ github.event.inputs.BROWSER }}
          mvn -B package --file pom.xml -Dbrowser="edge"

      - name: Execute on Firefox
        if: github.event.inputs.BROWSER == 'Firefox'
        run: |
          echo ${{ github.event.inputs.BROWSER }}
          mvn -B package --file pom.xml -Dbrowser="firefox"

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: src/resources/reports/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t kcvijay121/orangehrm-automation:latest

      - name: Push Docker image
        run: docker push kcvijay121/orangehrm-automation:latest
